var poemes = [
    [
        "Une femme borgne",
        "Une femme borgne pose nue dans mon fauteuil\nLa flamme de son oeil éclaire toute ma feuille\nLes formes de son corps s'articulent à la chaleur\nQue le coeur de son orbite intensifie chaque heure\n\nMes vers dépendent de son regard, s'il vacille\nJ'ouvre son oeil de force et je la déshabille\nEn fondant son revêtement je brûle mes doigts\nHeureusement elle n'est protégée d'aucune loi\n\nUne fois docile je peux voir son oeil azur\nJaunir son corps et lui donner toute une allure\nElle reste immobile et pourtant m'offre une danse\nEntre les pleurs de sa peau elle me laisse une chance\n\nJ'en profite alors j'approche ma main vers son sein\nJe vais trop vite et je garde des traces au matin\nDe ses réactions violentes à mes attouchements\nLa flamme de son coeur me fait battre jusqu'au sang\n\nFatigué à force de ne pas cligner, cet oeil\nEst innondé de larmes comme une femme en deuil\nEt je vide son orbite de pleurs dans l'évier\nLa muse peut reprendre position sans dévier\n\nLes fenêtres sont fumées et l'air ambiant s'affine\nTout son corps prend forme et des falaises se dessinent\nJe lui prend sa pudeur, elle me vole l'oxygène\nDe ma respiration, alors je souffle sans gène\n\nComme un vent déferlent sur son corps que j'ai perdu\nIl fait soudain noir et mon modèle a disparu\nJ'allume la lumière alors ma pupille ainsi\nDécouvre sur mon bureau une bougie finie\n\nFreskad",
    ],
    ["Elle sur lui", "Elle sur lui, noire sur blanc, et comme une tâche\nUn soir, une boule monochrome qui se cache\nLui sous elle, blanc sous noire, comme un paradis\nUne chambre qui contient les amoureux au lit\n\nLa forme se détend et prend place avec ses mains\nElle sort les dents et croque tendrement le coussin\nEt lui s'adapte à chaque mouvement de bord en bord\nIl s'incurve ou grossit selon la courbe du corps\n\nElle amusée, parcourt cette vallée de nuage\nLes courbures de l'amant se forment à ses passages\nLà où elle pose ses pattes, un creux se dessine\nOù se plante ses griffes, une montagne s'affine\n\nEt ses cheveux noirs font couler un fleuve de gras\nSur le beau blanc qui, serein, la calme dans ses bras\nEt ils voient que je les observe jalousement\nPourtant ne disent mot, et me fixent tendrement\n\nMoi, depuis mon bureau, je ne fais que contempler\nEux, mon chat noir et mon matelas blanc, s'amuser\n\nFreskad"],
    ["Les étoiles", "Les étoiles\nM'aiment et toi\nM'aimes-tu ? \nRépond-moi.\nTu t'es tu...\n\nLes étoiles \nParle moins\nMais au moins\nM'aiment plus\nMais me tuent\n\nTous leurs yeux\nAmoureux\nMe contemplent\nDans leur temple\nCéleste et\nÉtoilé\n\nEt pourtant\nLeurs lumières\nM'aveuglant\nNe m'éclairent\nAutant que\nTes deux yeux\n\nM'aimes-tu ?\nCar encore\nJ'ai perdu\nTout ton corps\n\nFreskad"],
    ["Regard de Pierre", "Ce regard froid de la pierre\nDans l'ombre, en claire lumière,\nQue dit-il, à toi qui erres ?\n\n« Jadis, une autre lumière,\nMon ami, sur notre terre,\nBrillait d'or sur cette terre,\nNotre vieille terre chère ;\n\nEt le chêne sur le tertre\nRecevait nos seules prières ;\nEt doré, l'habit du hêtre,\nProclamait le don de l'Être :\n\nLorsque, dorée, la lumière,\nIlluminait notre terre\nDu souvenir des ancêtres ;\n— Mon ami ! de nos ancêtres.\n\nAvant ce temps de misère ;\nQuand brillait d'or la lumière ;\nAvant cet âge de fer ;\nQuand fleurissaient les vieux tertres...\n\nÔ jeunesse de la terre !\nOù est passée ta lumière ? »\n\nGuillaume Balleraud"],
    ["Si loin est ma dame", "Si loin est ma dame, qui vient de loin :\nTrois massifs de montagnes nous séparent ;\nMais je sens ta présence qui s'empare\nDélicatement de mon être enclin\n\nÀ céder à ton charme jovial,\nÀ ton entrain joyeux nourri de rêves\nPleins de chaleur dans le temps hivernal,\nDans ta jeunesse brûlante en ses rêves.\n\nGuillaume Balleraud"],
    ["Si douce présence", "Si douce présence\nQui illumine mes jours et mes nuits\nMême en son absence\nElle est toujours présence ressentie\nSubtile dans l'air,\nParaissant si proche, comme une ardeur\nBaignant l'atmosphère ;\nMais comme une odeur sans aucune odeur.\n\nEtrange présence\nA la fois présente et pourtant absente\nQui échappe aux sens\nMais qui pourtant, languissante, apaisante,\nClaire se ressent\nAu creux du cœur par toi séduit, par toi\nÔ l'évanescente\nQui demeure en moi, nourrissant ma joie,\n\nToi qui es présence\nDrapée dans le secret de l'Invisible\nQui guide les sens\nVers l'espace ouvert de l'imperceptible ;\nEspace si doux\nOù se glissent mes pensées désirantes ;\nEspace pour nous,\nPour nous unir, avec toi mon absente.\n\nGuillaume Balleraud"],
    ["L'aurais-je rencontré", "L'aurais-je rencontrée dans un vieux bois\nRespirant tout ce qui est vieux, si vieux,\nPlus vieux que les jeunes arbres du bois,\nDu bois qui est de ses arbres plus vieux,\n\nQue point surpris me serais-je trouvé\nCar, pour sûr, d'un tel bois elle est la fée\nVenant parmi nous autres égarés,\nPerdus dans la grise modernité.\n\nGuillaume Balleraud"],
    ["Ainsi j'ai traversé", "Ainsi j'ai traversé des tempêtes de colère, des rivières de larmes\n\nMais la seule chose qui continue de m'emprisonner, c'est le silence de ton absence, la présence de ton absence.\n\nBlessure sur laquelle je m'appuie pour exister.\n\nJohn Joos"],
    ["Que ferais-je", "Que ferais-je de mes yeux,\nSi ce n'est de fixer les tiens,\n\nQue ferais-je de mes mains,\nSi ce n'est de tenir les tiennes,\n\nQue ferais-je de mon coeur,\nSi ce n'est de toujours t'aimer,\n\nQue ferais-je de mon Âme,\nSi ce n'est de l'enlacer éternellement à la tienne.\n\nJohn Joos"],
    ["Loin de moi", "Loin de moi\nUn\nCoin de toi\nPrend\nSoin de moi\nTu\nOins mes doigts\nPar\nMoins de loi\nEt\nPlus de coeur\n\nFreskad"],
];
